/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as IphoneRouteImport } from './routes/iphone'
import { Route as LectureRouteImport } from './routes/lecture'
import { Route as LimitsRouteImport } from './routes/limits'
import { Route as Mp3RouteImport } from './routes/mp3'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ZoomRouteImport } from './routes/zoom'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneRoute = IphoneRouteImport.update({
  id: '/iphone',
  path: '/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureRoute = LectureRouteImport.update({
  id: '/lecture',
  path: '/lecture',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsRoute = LimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const Mp3Route = Mp3RouteImport.update({
  id: '/mp3',
  path: '/mp3',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoomRoute = ZoomRouteImport.update({
  id: '/zoom',
  path: '/zoom',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/lecture': typeof LectureRoute
  '/limits': typeof LimitsRoute
  '/mp3': typeof Mp3Route
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zoom': typeof ZoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/lecture': typeof LectureRoute
  '/limits': typeof LimitsRoute
  '/mp3': typeof Mp3Route
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zoom': typeof ZoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/lecture': typeof LectureRoute
  '/limits': typeof LimitsRoute
  '/mp3': typeof Mp3Route
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/zoom': typeof ZoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-to'
    | '/iphone'
    | '/lecture'
    | '/limits'
    | '/mp3'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/zoom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-to'
    | '/iphone'
    | '/lecture'
    | '/limits'
    | '/mp3'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/zoom'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-to'
    | '/iphone'
    | '/lecture'
    | '/limits'
    | '/mp3'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/zoom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowToRoute: typeof HowToRoute
  IphoneRoute: typeof IphoneRoute
  LectureRoute: typeof LectureRoute
  LimitsRoute: typeof LimitsRoute
  Mp3Route: typeof Mp3Route
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ZoomRoute: typeof ZoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone': {
      id: '/iphone'
      path: '/iphone'
      fullPath: '/iphone'
      preLoaderRoute: typeof IphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture': {
      id: '/lecture'
      path: '/lecture'
      fullPath: '/lecture'
      preLoaderRoute: typeof LectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mp3': {
      id: '/mp3'
      path: '/mp3'
      fullPath: '/mp3'
      preLoaderRoute: typeof Mp3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoom': {
      id: '/zoom'
      path: '/zoom'
      fullPath: '/zoom'
      preLoaderRoute: typeof ZoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowToRoute: HowToRoute,
  IphoneRoute: IphoneRoute,
  LectureRoute: LectureRoute,
  LimitsRoute: LimitsRoute,
  Mp3Route: Mp3Route,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ZoomRoute: ZoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
